################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/demo_ce.c \
../Core/Src/logger.c \
../Core/Src/main.c \
../Core/Src/ndef_demo.c \
../Core/Src/ndef_dump.c \
../Core/Src/spi.c \
../Core/Src/stm32l4xx_hal_msp.c \
../Core/Src/stm32l4xx_it.c \
../Core/Src/syscalls.c \
../Core/Src/sysmem.c \
../Core/Src/system_stm32l4xx.c \
../Core/Src/usart.c 

OBJS += \
./Core/Src/demo_ce.o \
./Core/Src/logger.o \
./Core/Src/main.o \
./Core/Src/ndef_demo.o \
./Core/Src/ndef_dump.o \
./Core/Src/spi.o \
./Core/Src/stm32l4xx_hal_msp.o \
./Core/Src/stm32l4xx_it.o \
./Core/Src/syscalls.o \
./Core/Src/sysmem.o \
./Core/Src/system_stm32l4xx.o \
./Core/Src/usart.o 

C_DEPS += \
./Core/Src/demo_ce.d \
./Core/Src/logger.d \
./Core/Src/main.d \
./Core/Src/ndef_demo.d \
./Core/Src/ndef_dump.d \
./Core/Src/spi.d \
./Core/Src/stm32l4xx_hal_msp.d \
./Core/Src/stm32l4xx_it.d \
./Core/Src/syscalls.d \
./Core/Src/sysmem.d \
./Core/Src/system_stm32l4xx.d \
./Core/Src/usart.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/demo_ce.o: ../Core/Src/demo_ce.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/demo_ce.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/logger.o: ../Core/Src/logger.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/logger.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/main.o: ../Core/Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/ndef_demo.o: ../Core/Src/ndef_demo.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/ndef_demo.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/ndef_dump.o: ../Core/Src/ndef_dump.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/ndef_dump.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/spi.o: ../Core/Src/spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/spi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32l4xx_hal_msp.o: ../Core/Src/stm32l4xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32l4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32l4xx_it.o: ../Core/Src/stm32l4xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32l4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/syscalls.o: ../Core/Src/syscalls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/sysmem.o: ../Core/Src/sysmem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sysmem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/system_stm32l4xx.o: ../Core/Src/system_stm32l4xx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32l4xx.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/usart.o: ../Core/Src/usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L476xx -DDEBUG -c -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Core/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/Components/ST25R3911" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/NFC05A1" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/CMSIS/Include" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/message" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/ndef/Inc/poller" -I"C:/Users/Charles/STM32CubeIDE/workspace_1.4.0/test-nfc5/Middlewares/ST/rfal/Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/usart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

